sessions:
    pattern:  /
    defaults: { _controller: "EzapPublicBundle:Sessions:index" }

sessions_show:
    pattern:  /{id}/show
    defaults: { _controller: "EzapPublicBundle:Sessions:show" }

sessions_new:
    pattern:  /new
    defaults: { _controller: "EzapPublicBundle:Sessions:new" }

sessions_create:
    pattern:  /create
    defaults: { _controller: "EzapPublicBundle:Sessions:create" }
    requirements: { _method: post }

sessions_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EzapPublicBundle:Sessions:edit" }

sessions_update:
    pattern:  /{id}/update
    defaults: { _controller: "EzapPublicBundle:Sessions:update" }
    requirements: { _method: post|put }

sessions_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EzapPublicBundle:Sessions:delete" }
    requirements: { _method: post|delete }
