tags:
    pattern:  /
    defaults: { _controller: "EzapPublicBundle:Tags:index" }

tags_show:
    pattern:  /{id}/show
    defaults: { _controller: "EzapPublicBundle:Tags:show" }

tags_new:
    pattern:  /new
    defaults: { _controller: "EzapPublicBundle:Tags:new" }

tags_create:
    pattern:  /create
    defaults: { _controller: "EzapPublicBundle:Tags:create" }
    requirements: { _method: post }

tags_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EzapPublicBundle:Tags:edit" }

tags_update:
    pattern:  /{id}/update
    defaults: { _controller: "EzapPublicBundle:Tags:update" }
    requirements: { _method: post|put }

tags_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EzapPublicBundle:Tags:delete" }
    requirements: { _method: post|delete }
