imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@CinheticPublicBundle/Resources/config/config.yml' }
    - { resource: '@CinheticPublicBundle/Resources/config/services.yml' }

framework:
    default_locale: fr
    esi:             ~
    translator:      { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: CinheticPublicBundle::hinclude.html.twig
    default_locale:  fr
    trusted_hosts:   ~
    trusted_proxies: ~
    http_method_override: true
    session:
        cookie_lifetime: 30000
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true


sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
          - 'CinheticPublicBundle:Slots:forms.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["CinheticPublicBundle", "FOSUserBundle"]
    #java: /usr/bin/java
    filters:
     cssrewrite: ~
     uglifyjs:
      bin: '/usr/bin/uglifyjs'
#         less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
     coffee:
        bin: /usr/bin/coffee
        node: /usr/bin/node
        apply_to: "\.coffee$"
     sass:
        bin: /usr/local/bin/sass
     compass:
        bin: /usr/local/bin/compass
        apply_to: "\.s[ac]ss$"
     yui_css:
        jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
     closure:
        jar: "%kernel.root_dir%/Resources/java/googleclosure.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#Fos User Bundle
fos_user:
   db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
   firewall_name: main
   user_class:    Cinhetic\PublicBundle\Entity\User # La classe de l'entité User que nous utilisons



#Services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    twig.extension.debug:
       class: Twig_Extensions_Extension_Debug
       tags:
           - { name: twig.extension }
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }



#Elastic Search
fos_elastica:
    default_manager: orm
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            index_name: website_qa
            types:
              movies:
                mappings:
                    typeFilm: { type: string }
                    title: { type: string }
                    synopsis: { type: string }
                    description: { type: string }
                    bo: { type: string }
                    annee: { type: string }
                    budget: { type: string }
                    duree: { type: string }
                    dateRelease: { type: string }
                    actors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        city: { type: string }
                        biography: { type: string }
                        recompenses: { type: string }
                    cinemas:
                      type: "nested"
                      properties:
                        title: { type: string }
                        ville: { type: string }
                    directors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        biography: { type: string }
                    movies:
                        type: "nested"
                        properties:
                          title: { type: string }
                          synopsis: { type: string }
                          description: { type: string }
                    tags:
                        type: "nested"
                        properties:
                          word: { type: string }
                persistence:
                    driver: orm
                    model: Cinhetic\PublicBundle\Entity\Movies
                    repository: Cinhetic\PublicBundle\Repository\MoviesRepository
                    provider:
                        query_builder_method: getActiveMoviesBuilder
                    finder: ~
                    listener: ~ # by default, listens to "insert", "update" and "delete"


#KNP Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: CinheticPublicBundle:Slots:pagination.html.twig     # sliding pagination controls template


