imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@CinheticPublicBundle/Resources/config/config.yml' }
    - { resource: '@CinheticPublicBundle/Resources/config/services.yml' }

framework:
    default_locale: fr
    esi:             ~
    translator:      { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: CinheticPublicBundle::hinclude.html.twig
    default_locale:  fr
    trusted_hosts:   ~
    trusted_proxies: ~
    http_method_override: true
    session:
        cookie_lifetime: 30000
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true


sensio_framework_extra:
    view:
        annotations: false

# Rest APIs
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
          - 'CinheticPublicBundle:Slots:forms.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["CinheticPublicBundle", "FOSUserBundle"]
    #java: /usr/bin/java
    filters:
     cssrewrite: ~
     uglifyjs:
      bin: '/usr/bin/uglifyjs'
#         less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
     coffee:
        bin: /usr/bin/coffee
        node: /usr/bin/node
        apply_to: "\.coffee$"
     sass:
        bin: /usr/local/bin/sass
     compass:
        bin: /usr/local/bin/compass
        apply_to: "\.s[ac]ss$"
     yui_css:
        jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
     closure:
        jar: "%kernel.root_dir%/Resources/java/googleclosure.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
          default:
            filters:
              softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            dql:
             numeric_functions:
                 dateformat: Cinhetic\PublicBundle\AST\Functions\DateFormat
                 geo:  Cinhetic\PublicBundle\AST\Functions\Geo
                 age:  Cinhetic\PublicBundle\AST\Functions\Age
                 round:  Cinhetic\PublicBundle\AST\Functions\Round
            connection: default
            mappings:
              CinheticPublicBundle : ~
              gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree
                is_bundle: false

          site:
            connection: default
            mappings:
              CinheticPublicBundle : ~
        # query_cache_driver:    apc
        # metadata_cache_driver: apc
        # result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
   transport: gmail
   host:      smtp.gmail.com
   username:  "%mailer_user%"
   password:  "%mailer_password%"
   spool:     { type: memory }


#Fos User Bundle
fos_user:
   db_driver:     orm
   firewall_name: main
   user_class:    Cinhetic\PublicBundle\Entity\User


#Services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    twig.extension.debug:
       class: Twig_Extensions_Extension_Debug
       tags:
           - { name: twig.extension }
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }



#Elastic Search
fos_elastica:
    default_manager: orm
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            index_name: website_qa
            types:
              movies:
                mappings:
                    typeFilm: { type: string }
                    title: { type: string }
                    synopsis: { type: string }
                    description: { type: string }
                    bo: { type: string }
                    annee: { type: string }
                    budget: { type: string }
                    duree: { type: string }
                    dateRelease: { type: string }
                    actors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        city: { type: string }
                        biography: { type: string }
                        recompenses: { type: string }
                    cinemas:
                      type: "nested"
                      properties:
                        title: { type: string }
                        ville: { type: string }
                    directors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        biography: { type: string }
                    movies:
                        type: "nested"
                        properties:
                          title: { type: string }
                          synopsis: { type: string }
                          description: { type: string }
                    tags:
                        type: "nested"
                        properties:
                          word: { type: string }
                persistence:
                    driver: orm
                    model: Cinhetic\PublicBundle\Entity\Movies
                    repository: Cinhetic\PublicBundle\Repository\MoviesRepository
                    provider:
                        query_builder_method: getActiveMoviesBuilder
                    finder: ~
                    listener: ~ # by default, listens to "insert", "update" and "delete"


#KNP Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: CinheticPublicBundle:Slots:pagination.html.twig     # sliding pagination controls template


# Doctrine Extensions
stof_doctrine_extensions:
  orm:
    default:
      sluggable: true
      timestampable: true
      tree: true
      softdeleteable: true

#Lexik Paybox
lexik_paybox:
    servers:
      primary:
        system_path: '/cgi/modulev500-RhE5-64bits.cgi'
    parameters:
        site:  '1999888'   # Site number provided by the bank
        rank:  '32'        # Rank number provided by the bank
        login: '110647233' # Customer's login provided by Paybox
        hmac:
            key: '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF' # Key used to compute the hmac hash, provided by Paybox

#HWIOAuthBundle
hwi_oauth:
    connect:
      account_connector: fosubuser.provider
    firewall_name: main
    fosub:
      username_iterations: 30
      properties:
        facebook: facebook_id
        google: google_id
        twitter: twitter_id
        github: github_id
        linkedin: linkedin_id
        flickr: flickr_id
    resource_owners:
      github:
        type:                github
        client_id:           %api_github_id%
        client_secret:       %api_github_secret%
      twitter:
        type:                twitter
        client_id:           %api_twitter_id%
        client_secret:       %api_twitter_secret%
      google:
        type:                google
        client_id:           %api_google_id%
        client_secret:       %api_google_secret%
        scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
      facebook:
        type:                facebook
        client_id:           %api_facebook_id%
        client_secret:       %api_facebook_secret%
      linkedin:
        type:                linkedin
        client_id:           %api_linkedin_id%
        client_secret:       %api_linkedin_secret%
      flickr:
        type:                flickr
        client_id:           %api_flickr_id%
        client_secret:       %api_flickr_secret%



#Cinhetic Bundle
cinhetic_public:
  base_url: http://www.cinhetic.ju
  nb_movies_per_page: 7
  nb_categories_per_page: 5
  nb_actors_per_page: 4
  nb_directors_per_page: 4
  nb_comments_per_page: 10

