Cinhetic_public:
    resource: "@CinheticPublicBundle/Resources/config/routing.yml"
    prefix:   /administration

<<<<<<< HEAD
=======


>>>>>>> aca9a128d79191fc2afb629b6b8c461c0c7df410
#FOS Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


# My Authentification
fos_user_security_check:
    pattern:  /administration/login_check
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_logout:
    pattern:  /administration/logout
    defaults: { _controller: FOSUserBundle:Main:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /administration/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reseting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password


# Override FOSUser
CinheticPublicBundle_user:
    pattern:  /creation-de-compte
    defaults: { _controller: CinheticPublicBundle:Registration:register }

CinheticPublicBundle_profil:
    pattern:  /administration/mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:show }

CinheticPublicBundle_profil_edit:
    pattern:  /administration/editer-mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:edit }


# Homepage
homepage:
    pattern:  /
    defaults: { _controller: CinheticPublicBundle:Main:home }
    
oauth2callback:
    pattern:  /oauth2callback
    defaults: { _controller: CinheticPublicBundle:Main:home }

oauth2callback:
    pattern:  /oauth2callback
    defaults: { _controller: CinheticPublicBundle:Main:home }


# Tutoriaux API
apprentissage:
    pattern:  /apprentissage
    defaults: { _controller: CinheticPublicBundle:Main:apprentissage }

apprentissage_01:
    pattern:  /apprentissage/http-fondations-symfony2
    defaults: { _controller: CinheticPublicBundle:Main:one }

# Lexik paybox
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'


#HWIOAuthBundle routes

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth/login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /oauth/connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth/redirect

facebook_login:
    pattern: /oauth/login/check-facebook

github_login:
    pattern: /oauth/login/check-github

google_login:
    pattern: /oauth/login/check-google

oauth_target:
    pattern: /oauth/target
    defaults: { _controller: CinheticPublicBundle:Security:oauthTarget }


facebook_logout:
    pattern: /administration/logout
    defaults: { _controller: FOSUserBundle:Main:logout }

oauth_register:
    pattern: /oauthRegister
    defaults: { _controller: CinheticPublicBundle:Security:oauthRegister }

#Oauth Security
oauth_security_check:
    pattern:  /administration/login_check
    defaults: { _controller: FOSUserBundle:Security:login }

oauth_security_logout:
    pattern:  /administration/logout
    defaults: { _controller: FOSUserBundle:Main:logout }
