Cinhetic_public:
    resource: "@CinheticPublicBundle/Resources/config/routing.yml"
    prefix:   /administration


#FOS Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /administration/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reseting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password


# Override FOSUser
CinheticPublicBundle_user:
    pattern:  /creation-de-compte
    defaults: { _controller: CinheticPublicBundle:Registration:register }

CinheticPublicBundle_profil:
    pattern:  /administration/mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:show }

CinheticPublicBundle_profil_edit:
    pattern:  /administration/editer-mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:edit }


# Homepage
homepage:
    pattern:  /
    defaults: { _controller: CinheticPublicBundle:Main:home }


# Tutoriaux API
apprentissage:
    pattern:  /apprentissage
    defaults: { _controller: CinheticPublicBundle:Main:apprentissage }

apprentissage_01:
    pattern:  /apprentissage/http-fondations-symfony2
    defaults: { _controller: CinheticPublicBundle:Main:one }

# Lexik paybox
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'

# Authentification
fos_user_security_check:
    pattern:  /administration/login_check

fos_user_security_logout:
    pattern:  /administration/logout
    defaults: { _controller: FOSUserBundle:Security:logout }


#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook
