Cinhetic_public:
    resource: "@CinheticPublicBundle/Resources/config/routing.yml"
    prefix:   /


# Override FOSUser
CinheticPublicBundle_user:
    pattern:  /creation-de-compte
    defaults: { _controller: CinheticPublicBundle:Registration:register }

CinheticPublicBundle_profil:
    pattern:  /mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:show }

CinheticPublicBundle_profil_edit:
    pattern:  /editer-mon-compte
    defaults: { _controller: CinheticPublicBundle:Profile:edit }


oauth2callback:
    pattern:  /oauth2callback
    defaults: { _controller: CinheticPublicBundle:Main:home }

# Tutoriaux API
apprentissage:
    pattern:  /apprentissage
    defaults: { _controller: CinheticPublicBundle:Main:apprentissage }

apprentissage_01:
    pattern:  /apprentissage/http-fondations-symfony2
    defaults: { _controller: CinheticPublicBundle:Main:one }

# Lexik paybox
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'

facebook_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Main:logout }


# My Authentification

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Main:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reseting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /redirect

facebook_login:
    pattern: /login/check-facebook

github_login:
    pattern: /login/check-github

google_login:
    pattern: /login/check-google
