actors:
    pattern:  /
    defaults: { _controller: "CinheticPublicBundle:Actors:index" }

actors_show:
    pattern:  /{id}/show
    defaults: { _controller: "CinheticPublicBundle:Actors:show" }

actors_new:
    pattern:  /new
    defaults: { _controller: "CinheticPublicBundle:Actors:new" }

actors_create:
    pattern:  /create
    defaults: { _controller: "CinheticPublicBundle:Actors:create" }
    requirements: { _method: post }

actors_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CinheticPublicBundle:Actors:edit" }

actors_update:
    pattern:  /{id}/update
    defaults: { _controller: "CinheticPublicBundle:Actors:update" }
    requirements: { _method: post|put }

actors_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CinheticPublicBundle:Actors:delete" }
    requirements: { _method: post|delete }

actors_archived:
    pattern:  /archived/{id}
    defaults: { _controller: "CinheticPublicBundle:Actors:archived" }


# API Actors
actors_api_all:
  type: rest
  resource: Cinhetic\PublicBundle\Controller\ActorsController

actors_one_api:
  pattern: /{id}/one.{_format}
  defaults: { _controller: CinheticPublicBundle:Actors:one }

actors_all_api:
  pattern: /all.{_format}
  defaults: { _controller: CinheticPublicBundle:Actors:all }
