categories:
    pattern:  /
    defaults: { _controller: "CinheticPublicBundle:Categories:index" }

categories_show:
    pattern:  /{id}/show
    defaults: { _controller: "CinheticPublicBundle:Categories:show" }

categories_new:
    pattern:  /new
    defaults: { _controller: "CinheticPublicBundle:Categories:new" }

categories_create:
    pattern:  /create
    defaults: { _controller: "CinheticPublicBundle:Categories:create" }
    requirements: { _method: post }

categories_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CinheticPublicBundle:Categories:edit" }

categories_update:
    pattern:  /{id}/update
    defaults: { _controller: "CinheticPublicBundle:Categories:update" }
    requirements: { _method: post|put }

categories_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CinheticPublicBundle:Categories:delete" }
    requirements: { _method: post|delete }

# API Categories
categories_api_all:
  type: rest
  resource: Cinhetic\PublicBundle\Controller\CategoriesController

categories_one_api:
  pattern: /{id}/one.{_format}
  defaults: { _controller: CinheticPublicBundle:Categories:one }

categories_all_api:
  pattern: /all.{_format}
  defaults: { _controller: CinheticPublicBundle:Categories:all }
