movies:
    pattern:  /
    defaults: { _controller: "CinheticPublicBundle:Movies:index" }

movies_show:
    pattern:  /{id}/show
    defaults: { _controller: "CinheticPublicBundle:Movies:show" }

movies_new:
    pattern:  /new
    defaults: { _controller: "CinheticPublicBundle:Movies:new" }

movies_cities:
    pattern:  /city/{ville}
    defaults: { _controller: "CinheticPublicBundle:Movies:city" }

movies_activation:
    pattern:  /activation/{id}/{activation}
    defaults: { _controller: "CinheticPublicBundle:Movies:activation" }

movies_cover:
    pattern:  /cover/{id}/{cover}
    defaults: { _controller: "CinheticPublicBundle:Movies:cover" }

movies_create:
    pattern:  /create
    defaults: { _controller: "CinheticPublicBundle:Movies:create" }
    requirements: { _method: post }

movies_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CinheticPublicBundle:Movies:edit" }

movies_medias:
    pattern:  /{id}/medias
    defaults: { _controller: "CinheticPublicBundle:Movies:medias" }

movies_favoris:
    pattern:  /{id}/favoris
    defaults: { _controller: "CinheticPublicBundle:Movies:favoris" }

movies_update:
    pattern:  /{id}/update
    defaults: { _controller: "CinheticPublicBundle:Movies:update" }
    requirements: { _method: post|put }

movies_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CinheticPublicBundle:Movies:delete" }
    requirements: { _method: post|delete }

movies_delete_link:
    pattern:  /{id}/delete
    defaults: { _controller: "CinheticPublicBundle:Movies:deletelink" }

movies_archived:
    pattern:  /archived/{id}
    defaults: { _controller: "CinheticPublicBundle:Movies:archived" }


# API Movies
movies_api_all:
  type: rest
  resource: Cinhetic\PublicBundle\Controller\MoviesController

movies_one_api:
  pattern: /{id}/one.{_format}
  defaults: { _controller: CinheticPublicBundle:Movies:one }

movies_all_api:
  pattern: /all.{_format}
  defaults: { _controller: CinheticPublicBundle:Movies:all }
