# Homepage
ezap_public_homepage:
    pattern:  /
    defaults: { _controller: EzapPublicBundle:Main:index }

ezap_public_search:
    pattern:  /search
    defaults: { _controller: EzapPublicBundle:Main:index }


# Actors
EzapPublicBundle_actors:
    resource: "@EzapPublicBundle/Resources/config/routing/actors.yml"
    prefix:   /actors

# Movies
EzapPublicBundle_movies:
    resource: "@EzapPublicBundle/Resources/config/routing/movies.yml"
    prefix:   /movies

# Categories
EzapPublicBundle_categories:
  resource: "@EzapPublicBundle/Resources/config/routing/categories.yml"
  prefix:   /categories

# Cinema
EzapPublicBundle_cinema:
  resource: "@EzapPublicBundle/Resources/config/routing/cinema.yml"
  prefix:   /cinema

# Session
EzapPublicBundle_sessions:
    resource: "@EzapPublicBundle/Resources/config/routing/sessions.yml"
    prefix:   /sessions

# Tags
EzapPublicBundle_tags:
    resource: "@EzapPublicBundle/Resources/config/routing/tags.yml"
    prefix:   /tags

# Comments
EzapPublicBundle_comments:
    resource: "@EzapPublicBundle/Resources/config/routing/comments.yml"
    prefix:   /comments

