parameters:
    cinhetic_public.form_actors.class: Cinhetic\PublicBundle\Form\ActorsType
    cinhetic_public.form_directors.class: Cinhetic\PublicBundle\Form\DirectorsType
    cinhetic_public.form_categories.class: Cinhetic\PublicBundle\Form\CategoriesType
    cinhetic_public.form_cinema.class: Cinhetic\PublicBundle\Form\CinemaType
    cinhetic_public.form_comments.class: Cinhetic\PublicBundle\Form\CommentsType
    cinhetic_public.form_directors.class: Cinhetic\PublicBundle\Form\DirectorsType
    cinhetic_public.form_movies.class: Cinhetic\PublicBundle\Form\MoviesType
    cinhetic_public.form_sessions.class: Cinhetic\PublicBundle\Form\SessionsType
    cinhetic_public.form_tags.class: Cinhetic\PublicBundle\Form\TagsType
    cinhetic_public.form_comments.class: Cinhetic\PublicBundle\Form\CommentsType
    cinhetic_public.form_search.class: Cinhetic\PublicBundle\Form\SearchType
    cinhetic_public.manager_actors.class: Cinhetic\PublicBundle\Manager\ActorsManager
    cinhetic_public.manager_directors.class: Cinhetic\PublicBundle\Manager\DirectorsManager
    cinhetic_public.manager_categories.class: Cinhetic\PublicBundle\Manager\CategoriesManager
    cinhetic_public.manager_cinema.class: Cinhetic\PublicBundle\Manager\CinemaManager
    cinhetic_public.manager_movies.class: Cinhetic\PublicBundle\Manager\MoviesManager
    cinhetic_public.manager_sessions.class: Cinhetic\PublicBundle\Manager\SessionsManager
    cinhetic_public.manager_tags.class: Cinhetic\PublicBundle\Manager\TagsManager
    cinhetic_public.manager_comments.class: Cinhetic\PublicBundle\Manager\CommentsManager



services:

#    Form as Services
    cinhetic_public.form_actors:
        class: %cinhetic_public.form_actors.class%
        tags:
          - { name: form.type, alias: actors }

    cinhetic_public.manager_actors:
        scope: request
        class: %cinhetic_public.manager_actors.class%
        arguments: [@form.factory,@cinhetic_public.form_actors,@router,@doctrine.orm.entity_manager, @request, @validator]

    cinhetic_public.form_directors:
        class: %cinhetic_public.form_directors.class%
        tags:
          - { name: form.type, alias: actors }

    cinhetic_public.manager_directors:
        class: %cinhetic_public.manager_directors.class%
        arguments: [@form.factory,@cinhetic_public.form_directors,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_categories:
        class: %cinhetic_public.form_categories.class%
        tags:
          - { name: form.type, alias: categories }

    cinhetic_public.manager_categories:
        class: %cinhetic_public.manager_categories.class%
        arguments: [@form.factory,@cinhetic_public.form_categories,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_cinema:
        class: %cinhetic_public.form_cinema.class%
        tags:
          - { name: form.type, alias: cinemas }

    cinhetic_public.manager_cinema:
        class: %cinhetic_public.manager_cinema.class%
        arguments: [@form.factory,@cinhetic_public.form_cinema,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_movies:
        class: %cinhetic_public.form_movies.class%
        tags:
          - { name: form.type, alias: movies }

    cinhetic_public.manager_movies:
        class: %cinhetic_public.manager_movies.class%
        arguments: [@form.factory,@cinhetic_public.form_movies,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_sessions:
        class: %cinhetic_public.form_sessions.class%
        tags:
          - { name: form.type, alias: sessions }

    cinhetic_public.manager_sessions:
        class: %cinhetic_public.manager_sessions.class%
        arguments: [@form.factory,@cinhetic_public.form_sessions,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_tags:
        class: %cinhetic_public.form_tags.class%
        tags:
          - { name: form.type, alias: tags }

    cinhetic_public.manager_tags:
        class: %cinhetic_public.manager_tags.class%
        arguments: [@form.factory,@cinhetic_public.form_tags,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_comments:
        class: %cinhetic_public.form_comments.class%
        tags:
          - { name: form.type, alias: comments }

    cinhetic_public.manager_comments:
        class: %cinhetic_public.manager_comments.class%
        arguments: [@form.factory,@cinhetic_public.form_comments,@router,@doctrine.orm.entity_manager, @request]
        scope: request

    cinhetic_public.form_search:
        class: %cinhetic_public.form_search.class%
        tags:
          - { name: form.type, alias: search }
