parameters:
    cinhetic_public.form_actors.class: Cinhetic\PublicBundle\Form\ActorsType


services:

    # Repositories as service
    cinhetic_public.repository.movies:
      class: Cinhetic\PublicBundle\Repository\MoviesRepository
      factory_service: doctrine.orm.default_entity_manager
      factory_method: getRepository
      arguments:
        - Cinhetic\PublicBundle\Entity\Movies

    cinhetic_public.repository.cinema:
      class: Cinhetic\PublicBundle\Repository\CinemaRepository
      factory_service: doctrine.orm.default_entity_manager
      factory_method: getRepository
      arguments:
          - Cinhetic\PublicBundle\Entity\Cinema

    cinhetic_public.repository.actors:
      class: Cinhetic\PublicBundle\Repository\ActorsRepository
      factory_service: doctrine.orm.default_entity_manager
      factory_method: getRepository
      arguments:
        - Cinhetic\PublicBundle\Entity\Actors

    cinhetic_public.repository.sessions:
      class: Cinhetic\PublicBundle\Repository\SessionsRepository
      factory_service: doctrine.orm.default_entity_manager
      factory_method: getRepository
      arguments:
        - Cinhetic\PublicBundle\Entity\Sessions
