parameters:
    cinhetic_public.form_actors.class: Cinhetic\PublicBundle\Form\ActorsType
    cinhetic_public.form_directors.class: Cinhetic\PublicBundle\Form\DirectorsType
    cinhetic_public.form_categories.class: Cinhetic\PublicBundle\Form\CategoriesType
    cinhetic_public.form_cinema.class: Cinhetic\PublicBundle\Form\CinemaType
    cinhetic_public.form_comments.class: Cinhetic\PublicBundle\Form\CommentsType
    cinhetic_public.form_directors.class: Cinhetic\PublicBundle\Form\DirectorsType
    cinhetic_public.form_movies.class: Cinhetic\PublicBundle\Form\MoviesType
    cinhetic_public.form_sessions.class: Cinhetic\PublicBundle\Form\SessionsType
    cinhetic_public.form_tags.class: Cinhetic\PublicBundle\Form\TagsType
    cinhetic_public.form_comments.class: Cinhetic\PublicBundle\Form\CommentsType
    cinhetic_public.form_search.class: Cinhetic\PublicBundle\Form\SearchType
    cinhetic_public.manager_actors.class: Cinhetic\PublicBundle\Manager\ActorsManager
    cinhetic_public.manager_directors.class: Cinhetic\PublicBundle\Manager\DirectorsManager
    cinhetic_public.manager_categories.class: Cinhetic\PublicBundle\Manager\CategoriesManager
    cinhetic_public.manager_cinema.class: Cinhetic\PublicBundle\Manager\CinemaManager
    cinhetic_public.manager_movies.class: Cinhetic\PublicBundle\Manager\MoviesManager
    cinhetic_public.manager_sessions.class: Cinhetic\PublicBundle\Manager\SessionsManager
    cinhetic_public.manager_tags.class: Cinhetic\PublicBundle\Manager\TagsManager
    cinhetic_public.manager_comments.class: Cinhetic\PublicBundle\Manager\CommentsManager
    cinhetic_public.email.class: Cinhetic\PublicBundle\EmailDecorator\Email
    cinhetic_public.console_command.class: Cinhetic\PublicBundle\Command\EmailCommand
    cinhetic_public.handler_auth.class: Cinhetic\PublicBundle\Authentification\AuthentificationSiteHandler
    cinhetic_public.response_listener.class: Cinhetic\PublicBundle\Listener\IpnListener



services:

#   WebServicesFactory
    cinhetic_public.webservices:
      class: Cinhetic\PublicBundle\Webservice\WebServicesFactory
      arguments: [@guzzle.client]
#
##   Flickr service
#    cinhetic_public.webservice_flickr:
#      class: Cinhetic\PublicBundle\Webservice\Flickr
#      arguments: [@guzzle.client, %api_flickr_id%, %api_flickr_secret%]

#   Activity Listener
    cinhetic_public.activity.listener:
      class: Cinhetic\PublicBundle\Listener\ActivityListener
      arguments: [@security.context, @doctrine.orm.entity_manager]
      scope: request
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

#    Preexecute Method
    cinhetic_public.prexecute_listener:
      class:  Cinhetic\PublicBundle\Listener\PreMethodListener
      public: true
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

#   Form Search
    cinhetic_public.form_search:
        class: %cinhetic_public.form_search.class%
        tags:
          - { name: form.type, alias: search }

#    Handler authentification
    cinhetic_public.handler_auth:
        class: %cinhetic_public.handler_auth.class%
        arguments: [ @router, @doctrine.orm.entity_manager, @templating, @mailer ]


#    Add extension of twig
    cinhetic.twig.cinhetic_extension:
            class: Cinhetic\PublicBundle\Twig\CinheticExtension
            tags:
                - { name: twig.extension }

#    Command Console
    cinhetic_public.console_command:
        class: %cinhetic_public.console_command.class%
        tags:
          - { name: console.command }

#    Paybox Listener
    cinhetic_public.paybox.response_listener:
            class: %cinhetic_public.response_listener.class%
            arguments: [ %kernel.root_dir%, @filesystem ]
            tags:
                - { name: kernel.event_listener, event: paybox.ipn_response, method: onPayboxIpnResponse }

#     Email Service
    cinhetic_public.email:
      class: %cinhetic_public.email.class%
      arguments: [@templating, @mailer]


#     Facebook User Service
    fosubuser.provider:
      class: Cinhetic\PublicBundle\Security\User\Bridge\FOSUBUserProvider
      arguments: [@fos_user.user_manager,{facebook: facebookId, google: googleId, twitter: twitterId, github: githubId, linkedin: linkedinId, flickr: flickrId}]
