parameters:
#    cinhetic_public.example.class: Isap\PublicBundle\Example

services:
#    cinhetic_public.example:
#        class: %isap_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
