parameters:
#    cinhetic_public.example.class: Cinhetic\PublicBundle\Example

services:
#    cinhetic_public.example:
#        class: %cinhetic_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
