Directors:
    type: entity
    table: directors
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        biography:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        note:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        dateCreated:
            type: datetime
            nullable: true
            comment: ''
            column: date_created
    manyToMany:
        movies:
            targetEntity: Movies
            cascade: {  }
            mappedBy: null
            inversedBy: directors
            joinTable:
                name: directors_movies
                joinColumns:
                    -
                        name: directors_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: movies_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
